module.exports = {
  treasure: {
    type: 'text',
    name: 'Treasure',
    regex: /[Tt]reasure/,
    searchTerm: ' treasure',
  },
  'attack trigger': {
    type: 'text',
    name: 'Attack Trigger',
    regex: /[Ww]henever(.+)attack/,
    searchTerm: ' whenever attack',
  },
  'token maker': {
    type: 'text',
    name: 'Token Maker',
    regex: /create(.+)token/,
    searchTerm: ' create token',
  },
  'mana producer': {
    type: 'text',
    name: 'Mana Producer',
    regex: /[Aa]dd(.+)mana/,
    searchTerm: ' add mana',
  },
  ETB: {
    type: 'text',
    name: 'Enter Trigger',
    regex: / enter(.+)battlefield/,
    searchTerm: ' enter battlefield',
  },
  artifact: {
    type: 'text',
    name: 'Artifact Related',
    regex: / artifact/,
    searchTerm: ' artifact',
  },
  enchantment: {
    type: 'text',
    name: 'Enchantment Related',
    regex: / enchantment/,
    searchTerm: ' enchantment',
  },
  instant: {
    type: 'text',
    name: 'Instant Related',
    regex: / instant/,
    searchTerm: ' instant',
  },
  sorcery: {
    type: 'text',
    name: 'Sorcery Related',
    regex: /(?<!as a) sorcer(y|ies)/,
    searchTerm: ' sorcery',
  },
  creature: {
    type: 'text',
    name: 'Creature Related',
    regex: / creature/,
    searchTerm: ' creature',
  },
  land: {
    type: 'text',
    name: 'Land Related',
    regex: / land/,
    searchTerm: ' land',
  },
  'activated ability': {
    type: 'text',
    name: 'Activated Ability',
    regex: /:/,
    searchTerm: ' /:/',
  },
  //   lord: {
  //     type: 'text',
  //     name: 'lord',
  //     regex: /you control (get|have)(?!(.+)until)/,
  //     searchTerm: ' you control get or have -until',
  //   },
  'cost reduction': {
    type: 'text',
    name: 'Cost Reduction',
    regex: /cost(.+)less/,
    searchTerm: ' cost less',
  },
  discard: {
    type: 'text',
    name: 'Discard',
    regex: / discard/,
    searchTerm: ' discard',
  },
  //   debuff: {
  //     type: 'text',
  //     name: 'Debuff',
  //     regex: / -\d/,
  //     searchTerm: ' / -d/',
  //   },
}
