module.exports = {
  treasure: {
    description: 'Mentions treasure',
    type: 'text',
    name: 'Treasure',
    regex: /[Tt]reasure/,
    searchTerm: ' treasure',
  },
  'attack trigger': {
    description: 'Trigger on attack',
    type: 'text',
    name: 'Attack Trigger',
    regex: /[Ww]henever(.+)attack/,
    searchTerm: ' whenever attack',
  },
  'token maker': {
    description: 'Creates a token',
    type: 'text',
    name: 'Token Maker',
    regex: /[C|c]reate(.+)token/,
    searchTerm: ' create token',
  },
  'mana producer': {
    description: 'Produces mana',
    type: 'text',
    name: 'Mana Producer',
    regex: /[Aa]dd(.+)mana/,
    searchTerm: ' add mana',
  },
  ETB: {
    description: 'Triggers when it enters the battlefield',
    type: 'text',
    name: 'Enter Trigger',
    regex: / enter(.+)battlefield/,
    searchTerm: ' enter battlefield',
  },
  artifact: {
    description: 'Mentions artifacts',
    type: 'text',
    name: 'Artifact Related',
    regex: / artifact/,
    searchTerm: ' artifact',
  },
  enchantment: {
    description: 'Mentions enchantments',
    type: 'text',
    name: 'Enchantment Related',
    regex: / enchantment/,
    searchTerm: ' enchantment',
  },
  instant: {
    description: 'Mentions instants',
    type: 'text',
    name: 'Instant Related',
    regex: / instant/,
    searchTerm: ' instant',
  },
  sorcery: {
    description: 'Mentions sorceries',
    type: 'text',
    name: 'Sorcery Related',
    regex: /(?<!as a) sorcer(y|ies)/,
    searchTerm: ' sorcery',
  },
  creature: {
    description: 'Mentions creatures',
    type: 'text',
    name: 'Creature Related',
    regex: / creature/,
    searchTerm: ' creature',
  },
  land: {
    description: 'Mentions lands',
    type: 'text',
    name: 'Land Related',
    regex: / land/,
    searchTerm: ' land',
  },
  'activated ability': {
    description: 'Has an activated ability',
    type: 'text',
    name: 'Activated Ability',
    regex: /:/,
    searchTerm: ' /:/',
  },
  //   lord: {
  //     description: "",
  //     type: 'text',
  //     name: 'lord',
  //     regex: /you control (get|have)(?!(.+)until)/,
  //     searchTerm: ' you control get or have -until',
  //   },
  'cost reduction': {
    description: 'Has cost reduction',
    type: 'text',
    name: 'Cost Reduction',
    regex: /cost(.+)less/,
    searchTerm: ' cost less',
  },
  discard: {
    description: 'Mentions discard',
    type: 'text',
    name: 'Discard',
    regex: / discard/,
    searchTerm: ' discard',
  },
  debuff: {
    description: 'reduces stats',
    type: 'text',
    name: 'Debuff',
    regex: / -\d/,
    searchTerm: ' /-[0123456789]/',
  },
  buff: {
    description: 'increases stats',
    type: 'text',
    name: 'Buff',
    regex: / \+\d/,
    searchTerm: ' /\\+[0123456789]/ /\\//',
  },
  impulse: {
    description: 'plays cards exiled from top of library',
    type: 'text',
    name: 'Impulse Draw',
    regex: /(E|e)xile(.+)top(.+)library(.+)(Y|y)ou may (play|cast)/,
    searchTerm: ' exile top library may /(play|cast)/ /(those|that)/',
  },
  draw: {
    description: 'Mentions drawing cards',
    type: 'text',
    name: 'Draw',
    regex: /( d|D)raw /,
    searchTerm: ' draw',
  },
  dies: {
    description: 'Triggers on death',
    type: 'text',
    name: 'Death Trigger',
    regex: / dies?/,
    searchTerm: ' /\\sdies?/',
  },
  reanimate: {
    description: 'Returns from graveyard to battlefield',
    type: 'text',
    name: 'Reanimate',
    regex: / graveyards? onto the battlefield under/,
    searchTerm: ' from graveyard onto battlefield under -nontoken',
  },
  bounce: {
    description: 'Returns to hand',
    type: 'text',
    name: 'Bounce',
    // regex: /(R|r)eturn target(.+)to (its|their) owner('s|s') hand/,
    regex: /(R|r)eturn(?!.+graveyard)(.+)hand/,
    searchTerm: ' return hand -graveyard',
  },
  bind: {
    description: 'Prevents untapping',
    type: 'text',
    name: 'Bind',
    regex: /doesn't untap during/,
    searchTerm: " doesn't untap during",
  },
  freeCast: {
    description: 'Mentions spells cast for free',
    type: 'text',
    name: 'Free Cast',
    regex: /without paying (its|their) mana cost/,
    searchTerm: ' without paying mana cost',
  },
  theft: {
    description: 'Mentions playing other players cards',
    type: 'text',
    name: 'Theft',
    regex: /(opponent|to a player)(.+)as though it were mana/,
    searchTerm: ' /(opponent|to a player)/ though mana any color',
  },
  buttStrike: {
    description: 'Assigns damage with toughness rather than power',
    type: 'text',
    name: 'Butt Strike',
    regex: /rather than its power/,
    searchTerm: ' assign rather than power',
  },
  counterspell: {
    description: 'Counters a spell',
    type: 'text',
    name: 'Counterspell',
    regex: /(C|c)ounter target/,
    searchTerm: ' /(C|c)ounter\\starget/',
  },
  search: {
    description: 'Mentions searching',
    type: 'text',
    name: 'Search',
    regex: /(S|s)earch(.+)library/,
    searchTerm: ' /(S|s)earch/ library',
  },
  // dealsDamage: {
  //   description: 'Deals damage',
  //   type: 'text',
  //   name: 'Direct Damage',
  //   regex: /deals (\d|X)\d? damage/,
  //   searchTerm: ' /deals (\\d|X)\\d? damage/',
  // },
}
